### ISSUE TITLE
workers = int(os.environ.get('WORKERS'))

### ISSUE THREAD

**Issue by bamkikovic** [TerminalWarlord/TikTok-Downloader-Bot#12]
workers = int(os.environ.get('WORKERS'))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by OverStyleFR** [comment]
I have the same error

**Comment by sajjad-salam** [comment]
we have same error

**Comment by TerminalWarlord** [comment]
Try workers=4
