### ISSUE TITLE
int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by sajjad-salam** [TerminalWarlord/TikTok-Downloader-Bot#18]
int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
  File "C:\Users\sajjad\Downloads\TikTok-Downloader-Bot\main.py", line 23, in <module>
    workers = int(os.environ.get("4"))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

in this line
workers = int(os.environ.get("4"))

**Comment by TerminalWarlord** [comment]
Just simply add workers=4
