### ISSUE TITLE
WORKERS ERROR

### ISSUE THREAD

**Issue by mhmdrzkii** [TerminalWarlord/TikTok-Downloader-Bot#9]
i tried the code and got error like
`    workers = int(os.environ.get('2'))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'`

any solution?

**Comment by TerminalWarlord** [comment]
head over to https://github.com/TerminalWarlord/TikTok-Downloader-Bot/issues/3#issuecomment-1100818061
